# curl -X 'PUT'
#  'http://localhost:8080/songs'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "group": "Muse",
#  "song": "Supermassive Black Hole",
#  "songDetail": {
#    "releaseDate": "16.07.2008",
#    "text": "Ooh baby, don t you know I suffer?",
#    "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
#  }
#}'
PUT http://localhost:8080/songs
accept: */*
Content-Type: application/json

{
  "group": "Muse",
  "song": "Supermassive Black Hole",
  "songDetail": {
    "releaseDate": "16.07.2008",
    "text": "Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight",
    "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
  }
}

###

# Empty request

PUT http://localhost:8080/songs
accept: */*
Content-Type: application/json

{
  "group": "Muse",
  "song": "Supermassive Black Hole",
  "songDetail": {
    "releaseDate": "",
    "text": "",
    "link": ""
  }
}

###

# Wrong date

PUT http://localhost:8080/songs
accept: */*
Content-Type: application/json

{
  "group": "Muse",
  "song": "Supermassive Black Hole",
  "songDetail": {
    "releaseDate": "22.15.2011",
    "text": "",
    "link": ""
  }
}

###