# curl -X 'GET'
#  'http://localhost:8080/songs/text?group=Muse&song=Supermassive%20Black%20Hole&page=1'
#  -H 'accept: application/json'
GET http://localhost:8080/songs/text?
    group=Muse&
    song=Supermassive%20Black%20Hole&
    page=2
accept: application/json

###

# Wrong song
GET http://localhost:8080/songs/text?
    group=Wrong%20group&
    song=Wrong%20song&
    page=1
accept: application/json

###

# Bad request: no page
GET http://localhost:8080/songs/text?
    group=Wrong%20group&
    song=Wrong%20song
accept: application/json

###
