// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SongDeleter is an autogenerated mock type for the SongDeleter type
type SongDeleter struct {
	mock.Mock
}

// SongDelete provides a mock function with given fields: groupName, songName
func (_m *SongDeleter) SongDelete(groupName string, songName string) (int, error) {
	ret := _m.Called(groupName, songName)

	if len(ret) == 0 {
		panic("no return value specified for SongDelete")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(groupName, songName)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(groupName, songName)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(groupName, songName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSongDeleter creates a new instance of SongDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSongDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SongDeleter {
	mock := &SongDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
